region               = "us-east-1"
lab_role_arn         = "arn:aws:iam::650380094581:role/LabRole"
session_token_aws    = 
access_key_aws       = 
secret_aws           = 
input_sqs_url        = 
sqs_message_group    = "TC"
sqs_polling_interval = "5000"
secret_key_jwt_token = 