name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_access_key_aws: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_session_token_aws: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_secret_aws: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_lab_role_arn: ${{ vars.TF_VAR_LAB_ROLE_ARN }}
      TF_VAR_sqs_polling_interval: ${{ vars.TF_VAR_SQS_POLLING_INTERVAL }}
      TF_VAR_sqs_message_group: ${{ vars.TF_VAR_SQS_MESSAGE_GROUP }}
      TF_VAR_order_received: ${{ vars.TF_VAR_ORDER_RECEIVED }}
      TF_VAR_queue_finished: ${{ vars.TF_VAR_QUEUE_FINISHED }}
      TF_VAR_secret_key_jwt_token: ${{ secrets.TF_VAR_SECRET_KEY_JWT_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          terraform init -backend-config="bucket=${{vars.TF_VAR_TFSTATE_QUEUE}}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"
        
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve